AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: comfort-generate-chatbot

Globals:
  Function:
    Timeout: 16
    MemorySize: 128

    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  ChatbotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: service/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Architectures:
      - arm64
      Events:
        Chatbot:
          Type: HttpApi
          Properties:
            Path: /kakao
            Method: post
      Policies:
      - AmazonDynamoDBFullAccess


Outputs:
  ChatbotHttpApi:
    Description: API Gateway endpoint URL for Prod stage for Chatbot function
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/kakao/"
  ChatbotFunction:
    Description: Chatbot Lambda Function ARN
    Value: !GetAtt ChatbotFunction.Arn
  ChatbotFunctionIamRole:
    Description: Implicit IAM Role created for Chatbot function
    Value: !GetAtt ChatbotFunctionRole.Arn
